export default {
    50: {
      "key": 0,
      "label": "Цена за доп. пакет 50 км / день",
      "placeholder": "Например 7",
      "name": "50km",
      "labelForAdd": "50 км",
    },
    100: {
      "key": 1,
      "label": "Цена за доп. пакет 100 км / день",
      "placeholder": "Например 10",
      "name": "100km",
      "labelForAdd": "100 км",
    },
    200: {
      "key": 2,
      "label": "Цена за доп. пакет 200 км / день",
      "placeholder": "Например 12",
      "name": "200km",
      "labelForAdd": "200 км",
    },
    300: {
      "key": 3,
      "label": "Цена за доп. пакет 300 км / день",
      "placeholder": "Например 15",
      "name": "300km",
      "labelForAdd": "300 км",
    },
    400: {
      "key": 4,
      "label": "Цена за доп. пакет 400 км / день",
      "placeholder": "Например 20",
      "name": "400km",
      "labelForAdd": "400 км",
    },
    500: {
      "key": 5,
      "label": "Цена за доп. пакет 500 км / день",
      "placeholder": "Например 25",
      "name": "500km",
      "labelForAdd": "500 км",
    },
    600: {
      "key": 6,
      "label": "Цена за доп. пакет 600 км / день",
      "placeholder": "Например 30",
      "name": "600km",
      "labelForAdd": "600 км",
    },
    700: {
      "key": 7,
      "label": "Цена за доп. пакет 700 км / день",
      "placeholder": "Например 45",
      "name": "700km",
      "labelForAdd": "700 км",
    },
    800: {
      "key": 8,
      "label": "Цена за доп. пакет 800 км / день",
      "placeholder": "Например 55",
      "name": "800km",
      "labelForAdd": "800 км",
    },
    900: {
      "key": 9,
      "label": "Цена за доп. пакет 900 км / день",
      "placeholder": "Например 65",
      "name": "900km",
      "labelForAdd": "900 км",
    },
    "infinity": {
      "key": 10,
      "label": "Цена за неограниченный пробег / день",
      "placeholder": "Например 75",
      "name": "infinity",
      "labelForAdd": "Неограниченный пробег",
    }
  }