export const FEATURES = [
	{
		name: 'CHILD_SEAT',
		label: 'Детское кресло',
		value: false,
		price: 15,
		unit: 'день',
	},
	{
		name: 'NAVIGATOR',
		label: 'Навигатор',
		value: false,
		price: 15,
		unit: 'день',
	},
	{
		name: 'REGISTRATOR',
		label: 'Регистратор',
		value: false,
		price: 15,
		unit: 'день',
	},
	{
		name: 'RADAR_DETECTOR',
		label: 'Антирадар',
		value: false,
		price: 15,
		unit: 'день',
	},
	{
		name: 'ROOF_RACK',
		label: 'Багажник на крыше',
		value: true,
		price: 15,
		unit: 'день',
	},
	{
		name: 'FRIDGE',
		label: 'Холодильник',
		value: false,
		price: 15,
		unit: 'день',
	},
	{
		name: 'BIKE_RACK',
		label: 'Крепление для велосипеда',
		value: false,
		price: 15,
		unit: 'день',
	},
	{
		name: 'SNOWBOARD_RACK',
		label: 'Крепление для сноуборда',
		value: false,
		price: 15,
		unit: '',
	},
	{
		name: 'SKIING_RACK',
		label: 'Крепление для лыж',
		value: false,
		price: 15,
		unit: '',
	},
];
