export const PROLONGATION_SOLUTION = {
  HOST_CONFIRM: "HOST_CONFIRM",
  HOST_CANCEL: "HOST_CANCEL",
  GUEST_CANCEL: "GUEST_CANCEL",
}

export const PROLONGATION_STATUS = {
  RENT_PROLONGATION_REQUEST: "RENT_PROLONGATION_REQUEST",
  RENT_PROLONGATION_ACCEPTED: "RENT_PROLONGATION_ACCEPTED",
  RENT_PROLONGATION_GUEST_DECLINED: "RENT_PROLONGATION_GUEST_DECLINED",
  RENT_PROLONGATION_HOST_DECLINED: "RENT_PROLONGATION_HOST_DECLINED",
}
