export const STATUSES = {
	AWAITS_INITIAL_PAYMENT: 'AWAITS_INITIAL_PAYMENT',
	AWAITS_UPDATE_PAYMENT: 'AWAITS_UPDATE_PAYMENT',
	AWAITS_GUEST_SCORING_COMPLETION: 'AWAITS_GUEST_SCORING_COMPLETION',
	AWAITS_HOST_APPROVAL: 'AWAITS_HOST_APPROVAL',
	APPROVED_BY_HOST: 'APPROVED_BY_HOST',
	IN_PROGRESS: 'IN_PROGRESS',
	FINISHED: 'FINISHED',
	DECLINED_AUTOMATICALLY: 'DECLINED_AUTOMATICALLY',
	DECLINED_BY_HOST: 'DECLINED_BY_HOST',
	DECLINED_BY_GUEST: 'DECLINED_BY_GUEST',
	REJECTED: 'REJECTED',
};
