export const
	LOAD_HOST_PREFERENCES_REQUEST = 'LOAD_HOST_PREFERENCES_REQUEST',
	UPDATE_HOST_WORKING_HOURS_REQUEST = 'UPDATE_HOST_WORKING_HOURS_REQUEST',
	UPDATE_HOST_BIO_REQUEST = 'UPDATE_HOST_BIO_REQUEST',
	LOAD_HOST_PREFERENCES = 'LOAD_HOST_PREFERENCES',
	LOAD_HOST_PAYMENT_METHOD_REQUEST = 'LOAD_HOST_PAYMENT_METHOD_REQUEST',
	SET_HOST_PAYMENT_METHOD_REQUEST = 'SET_HOST_PAYMENT_METHOD_REQUEST',
	SET_HOST_PAYMENT_METHOD = 'SET_HOST_PAYMENT_METHOD',
	RESET_HOST = 'RESET_HOST',
	SET_HOST_LOADER = 'SET_HOST_LOADER'