export default {
    "AC": {
        "models": ["378 GT Zagato", "Ace", "Aceca", "Cobra"]
      },
      "AMC": {
        "models": ["Eagle", "Hornet"]
      },
      "Acura": {
        "models": [
          "CL",
          "CSX",
          "EL",
          "ILX",
          "Integra",
          "Legend",
          "MDX",
          "NSX",
          "RDX",
          "RL",
          "RLX",
          "RSX",
          "SLX",
          "TL",
          "TLX",
          "TSX",
          "ZDX"
        ]
      },
      "Adler": {
        "models": ["Diplomat", "Trumpf Junior"]
      },
      "Alfa Romeo": {
        "models": [
          "105/115",
          "145",
          "146",
          "147",
          "155",
          "156",
          "159",
          "164",
          "166",
          "1900",
          "2600",
          "33",
          "4C",
          "6",
          "6C",
          "75",
          "8C Competizione",
          "90",
          "Alfasud",
          "Alfetta",
          "Arna",
          "Brera",
          "Disco Volante",
          "Giulia",
          "Giulietta",
          "GT",
          "GTA Coupe",
          "GTV",
          "MiTo",
          "Montreal",
          "RZ",
          "Spider",
          "Sprint",
          "Stelvio",
          "SZ"
        ]
      },
      "Alpina": {
        "models": [
          "B10",
          "B11",
          "B12",
          "B3",
          "B4",
          "B5",
          "B6",
          "B7",
          "B8",
          "B9",
          "C1",
          "C2",
          "D10",
          "D3",
          "D4",
          "D5",
          "Roadster",
          "XD3"
        ]
      },
      "Aro": {
        "models": ["10", "24"]
      },
      "Asia": {
        "models": ["Retona", "Rocsta", "Topic"]
      },
      "Aston Martin": {
        "models": [
          "Bulldog",
          "Cygnet",
          "DB AR1",
          "DB11",
          "DB5",
          "DB7",
          "DB9",
          "DBS",
          "Lagonda",
          "One-77",
          "Rapide",
          "Tickford Capri",
          "V12 Vantage",
          "V12 Zagato",
          "V8 Vantage",
          "V8 Zagato",
          "Vanquish",
          "Virage"
        ]
      },
      "Audi": {
        "models": [
          "100",
          "200",
          "50",
          "80",
          "90",
          "920",
          "A1",
          "A2",
          "A3",
          "A4",
          "A4 allroad",
          "A5",
          "A6",
          "A6 allroad",
          "A7",
          "A8",
          "Cabriolet",
          "Coupe",
          "e-tron",
          "NSU RO 80",
          "Q2",
          "Q3",
          "Q3 Sportback",
          "Q5",
          "Q7",
          "Q8",
          "Quattro",
          "R8",
          "RS 2",
          "RS 3",
          "RS 4",
          "RS 5",
          "RS 6",
          "RS 7",
          "RS Q3",
          "S1",
          "S2",
          "S3",
          "S4",
          "S5",
          "S6",
          "S7",
          "S8",
          "SQ2",
          "SQ5",
          "SQ7",
          "SQ8",
          "TT",
          "TT RS",
          "TTS",
          "Typ R",
          "V8"
        ]
      },
      "Austin": {
        "models": [
          "Allegro",
          "Ambassador",
          "Maestro",
          "Maxi",
          "Metro",
          "Mini",
          "Montego",
          "Princess",
          "Sprite"
        ]
      },
      "Austin Healey": {
        "models": ["3000"]
      },
      "BAIC": {
        "models": ["A1", "BJ2020", "BJ212", "EU260", "Jeep Cherokee 2500", "Luba (XB624)"]
      },
      "BMW": {
        "models": [
          "02 (E10)",
          "1 \u0441\u0435\u0440\u0438\u044f",
          "1M",
          "2 \u0441\u0435\u0440\u0438\u044f",
          "2 \u0441\u0435\u0440\u0438\u044f Active Tourer",
          "2 \u0441\u0435\u0440\u0438\u044f Grand Tourer",
          "2000 C/CS",
          "3 \u0441\u0435\u0440\u0438\u044f",
          "3/15",
          "315",
          "3200",
          "321",
          "326",
          "327",
          "340",
          "4 \u0441\u0435\u0440\u0438\u044f",
          "5 \u0441\u0435\u0440\u0438\u044f",
          "501",
          "502",
          "503",
          "507",
          "6 \u0441\u0435\u0440\u0438\u044f",
          "600",
          "7 \u0441\u0435\u0440\u0438\u044f",
          "700",
          "8 \u0441\u0435\u0440\u0438\u044f",
          "E3",
          "E9",
          "i3",
          "i8",
          "M2",
          "M3",
          "M4",
          "M5",
          "M6",
          "M8",
          "New Class",
          "X1",
          "X2",
          "X3",
          "X3 M",
          "X4",
          "X4 M",
          "X5",
          "X5 M",
          "X6",
          "X6 M",
          "X7",
          "Z1",
          "Z3",
          "Z3 M",
          "Z4",
          "Z4 M",
          "Z8"
        ]
      },
      "BYD": {
        "models": ["E6", "F0", "F3", "F5", "F6", "F8 (S8)", "Flyer", "G3", "G6", "L3", "M6", "S6"]
      },
      "Bajaj": {
        "models": ["Qute"]
      },
      "Baltijas Dzips": {
        "models": ["BD-1322"]
      },
      "Batmobile": {
        "models": ["1989", "2018"]
      },
      "Bentley": {
        "models": [
          "Arnage",
          "Azure",
          "Bentayga",
          "Brooklands",
          "Continental",
          "Continental Flying Spur",
          "Continental GT",
          "Eight",
          "Flying Spur",
          "Mark VI",
          "Mulsanne",
          "R Type",
          "S",
          "T-Series",
          "Turbo R"
        ]
      },
      "Borgward": {
        "models": ["2000", "Hansa 1100"]
      },
      "Brilliance": {
        "models": ["FRV (BS2)", "H230", "H530", "M1 (BS6)", "M2 (BS4)", "M3 (BC3)", "V3", "V5"]
      },
      "Bugatti": {
        "models": ["Chiron", "EB 110", "EB 112", "EB Veyron 16.4", "Type 55"]
      },
      "Buick": {
        "models": [
          "Century",
          "Electra",
          "Enclave",
          "Encore",
          "Envision",
          "Estate Wagon",
          "Excelle",
          "GL8",
          "GS",
          "LaCrosse",
          "LeSabre",
          "Limited",
          "Lucerne",
          "Park Avenue",
          "Rainer",
          "Reatta",
          "Regal",
          "Rendezvous",
          "Riviera",
          "Roadmaster",
          "Skyhawk",
          "Skylark",
          "Special",
          "Super",
          "Terraza",
          "Verano",
          "Wildcat"
        ]
      },
      "Cadillac": {
        "models": [
          "Allante",
          "ATS",
          "ATS-V",
          "BLS",
          "Brougham",
          "Catera",
          "CT5",
          "CT6",
          "CTS",
          "CTS-V",
          "DeVille",
          "DTS",
          "Eldorado",
          "ELR",
          "Escalade",
          "Fleetwood",
          "LSE",
          "Series 62",
          "Seville",
          "Sixty Special",
          "SRX",
          "STS",
          "XLR",
          "XT4",
          "XT5",
          "XT6",
          "XTS"
        ]
      },
      "Chana": {
        "models": ["Benni"]
      },
      "ChangFeng": {
        "models": ["Flying", "SUV (CS6)"]
      },
      "Changan": {
        "models": [
          "Alsvin V7",
          "Benni",
          "CM-8",
          "CS35",
          "CS35PLUS",
          "CS75",
          "CX20",
          "Eado",
          "Raeton",
          "Z-Shine"
        ]
      },
      "Changhe": {
        "models": ["Ideal"]
      },
      "Chery": {
        "models": [
          "Amulet (A15)",
          "Arrizo 3",
          "Arrizo 7",
          "B13",
          "Bonus (A13)",
          "Bonus 3 (E3/A19)",
          "CrossEastar (B14)",
          "Fora (A21)",
          "IndiS (S18D)",
          "Karry",
          "Kimo (A1)",
          "M11 (A3)",
          "Oriental Son (B11)",
          "QQ6 (S21)",
          "QQme",
          "Sweet (QQ)",
          "Tiggo (T11)",
          "Tiggo 2",
          "Tiggo 3",
          "Tiggo 4",
          "Tiggo 5",
          "Tiggo 7",
          "Tiggo 7 Pro",
          "Tiggo 8 Pro",
          "Very (A13)",
          "Windcloud (A11)"
        ]
      },
      "Chevrolet": {
        "models": [
          "Alero",
          "Astra",
          "Astro",
          "Avalanche",
          "Aveo",
          "Bel Air",
          "Beretta",
          "Blazer",
          "Blazer K5",
          "Bolt",
          "C-10",
          "C/K",
          "Camaro",
          "Caprice",
          "Captiva",
          "Cavalier",
          "Celebrity",
          "Celta",
          "Chevelle",
          "Chevette",
          "Citation",
          "Classic",
          "Cobalt",
          "Colorado",
          "Corsa",
          "Corsica",
          "Corvair",
          "Corvette",
          "Cruze",
          "Cruze (HR)",
          "CSV CR8",
          "Deluxe",
          "El Camino",
          "Epica",
          "Equinox",
          "Evanda",
          "Express",
          "Fleetmaster",
          "HHR",
          "Impala",
          "Kalos",
          "Lacetti",
          "Lanos",
          "Lumina",
          "Lumina APV",
          "LUV D-MAX",
          "Malibu",
          "Master",
          "Matiz",
          "Metro",
          "Monte Carlo",
          "Monza",
          "MW",
          "Niva",
          "Nubira",
          "Omega",
          "Orlando",
          "Prizm",
          "Rezzo",
          "S-10 Pickup",
          "Sail",
          "Silverado",
          "Sonic",
          "Spark",
          "Special DeLuxe",
          "Spin",
          "SS",
          "SSR",
          "Starcraft",
          "Suburban",
          "Tacuma",
          "Tahoe",
          "Tavera",
          "Tracker",
          "TrailBlazer",
          "Trans Sport",
          "Traverse",
          "Uplander",
          "Van",
          "Vectra",
          "Venture",
          "Viva",
          "Volt",
          "Zafira"
        ]
      },
      "Chrysler": {
        "models": [
          "180",
          "200",
          "300",
          "300 Letter Series",
          "300C",
          "300M",
          "Aspen",
          "Cirrus",
          "Concorde",
          "Cordoba",
          "Crossfire",
          "Daytona",
          "Dynasty",
          "Fifth Avenue",
          "Imperial",
          "Imperial Crown",
          "Intrepid",
          "LeBaron",
          "LHS",
          "Nassau",
          "Neon",
          "New Yorker",
          "Newport",
          "Pacifica",
          "Prowler",
          "PT Cruiser",
          "Saratoga",
          "Sebring",
          "Stratus",
          "TC by Maserati",
          "Town & Country",
          "Viper",
          "Vision",
          "Voyager",
          "Windsor"
        ]
      },
      "Citroen": {
        "models": [
          "2 CV",
          "AMI",
          "AX",
          "Berlingo",
          "BX",
          "C-Crosser",
          "C-Elysee",
          "C-Quatre",
          "C-Triomphe",
          "C-ZERO",
          "C1",
          "C2",
          "C3",
          "C3 Aircross",
          "C3 Picasso",
          "C4",
          "C4 Aircross",
          "C4 Cactus",
          "C4 Picasso",
          "C4 SpaceTourer",
          "C5",
          "C5 Aircross",
          "C6",
          "C8",
          "CX",
          "DS",
          "DS3",
          "DS4",
          "DS5",
          "Dyane",
          "E-Mehari",
          "Evasion",
          "GS",
          "Jumpy",
          "LN",
          "Nemo",
          "Saxo",
          "SM",
          "SpaceTourer",
          "Traction Avant",
          "Visa",
          "Xantia",
          "XM",
          "Xsara",
          "Xsara Picasso",
          "ZX"
        ]
      },
      "DKW": {
        "models": ["3=6"]
      },
      "DS": {
        "models": ["3", "4", "5", "7 Crossback"]
      },
      "DW Hower": {
        "models": ["H3", "H5"]
      },
      "Dacia": {
        "models": [
          "1300",
          "1310",
          "1325",
          "1410",
          "Dokker",
          "Duster",
          "Lodgy",
          "Logan",
          "Nova",
          "Pick-Up",
          "Sandero",
          "Solenza",
          "SuperNova"
        ]
      },
      "Dadi": {
        "models": ["City Leading", "Shuttle", "Smoothing"]
      },
      "Daewoo": {
        "models": [
          "Alpheon",
          "Arcadia",
          "Chairman",
          "Damas",
          "Espero",
          "Evanda",
          "G2X",
          "Gentra",
          "Kalos",
          "Korando",
          "Lacetti",
          "Lacetti Premiere",
          "Lanos",
          "Leganza",
          "LeMans",
          "Magnus",
          "Matiz",
          "Matiz Creative",
          "Musso",
          "Nexia",
          "Nubira",
          "Prince",
          "Racer",
          "Rezzo",
          "Royale",
          "Sens",
          "Tacuma",
          "Tico",
          "Tosca",
          "Winstorm"
        ]
      },
      "Daihatsu": {
        "models": [
          "Altis",
          "Applause",
          "Atrai",
          "Be-go",
          "Bee",
          "Boon",
          "Boon Luminas",
          "Ceria",
          "Charade",
          "Charmant",
          "Coo",
          "Copen",
          "Cuore",
          "Delta Wagon",
          "Esse",
          "Fellow",
          "Feroza",
          "Gran Move",
          "Hijet",
          "Leeza",
          "Materia",
          "MAX",
          "Midget",
          "Mira",
          "Mira e:S",
          "Mira Gino",
          "Move",
          "Move Canbus",
          "Move Conte",
          "Move Latte",
          "Naked",
          "Opti",
          "Pyzar",
          "Rocky",
          "Rugger",
          "Sirion",
          "Sonica",
          "Storia",
          "Taft",
          "Tanto",
          "Tanto Exe",
          "Terios",
          "Trevis",
          "Wildcat",
          "Xenia",
          "YRV"
        ]
      },
      "Daimler": {
        "models": ["DS420", "Sovereign (XJ6)", "SP250", "X300", "X308", "X350", "XJ40", "XJS"]
      },
      "Datsun": {
        "models": [
          "240Z",
          "280ZX",
          "720",
          "Bluebird",
          "Cherry",
          "GO",
          "GO+",
          "Laurel",
          "mi-DO",
          "on-DO",
          "Stanza",
          "Sunny",
          "Urvan",
          "Violet"
        ]
      },
      "De Tomaso": {
        "models": ["Bigua", "Guara", "Mangusta", "Pantera", "Vallelunga"]
      },
      "DeLorean": {
        "models": ["DMC-12"]
      },
      "Derways": {
        "models": ["Antelope", "Aurora", "Cowboy", "Land Crown", "Plutus", "Saladin", "Shuttle"]
      },
      "Dodge": {
        "models": [
          "600",
          "Aries",
          "Avenger",
          "Caliber",
          "Caravan",
          "Challenger",
          "Charger",
          "Charger Daytona",
          "Colt",
          "Custom Royal",
          "D/W Series",
          "D8",
          "Dakota",
          "Dart",
          "Daytona",
          "Diplomat",
          "Durango",
          "Dynasty",
          "Intrepid",
          "Journey",
          "Lancer",
          "Magnum",
          "Mayfair",
          "Monaco",
          "Neon",
          "Nitro",
          "Omni",
          "Raider",
          "RAM",
          "Ramcharger",
          "Shadow",
          "Spirit",
          "Stealth",
          "Stratus",
          "Viper",
          "WC series"
        ]
      },
      "DongFeng": {
        "models": ["370", "580", "A30", "A9", "AX7", "H30 Cross", "MPV", "Oting", "Rich", "S30"]
      },
      "Doninvest": {
        "models": ["Assol", "Kondor", "Orion"]
      },
      "Eagle": {
        "models": ["Premier", "Summit", "Talon", "Vision"]
      },
      "Excalibur": {
        "models": ["Series IV", "Series V"]
      },
      "FAW": {
        "models": [
          "Besturn B50",
          "Besturn B70",
          "Besturn X40",
          "Besturn X80",
          "Jinn",
          "Oley",
          "V2",
          "V5",
          "Vita"
        ]
      },
      "FSO": {
        "models": ["125p", "126p", "127p", "132p", "Polonez"]
      },
      "Ferrari": {
        "models": [
          "250 GTO",
          "328",
          "348",
          "360",
          "400",
          "412",
          "456",
          "458",
          "488",
          "512 BB",
          "512 M",
          "512 TR",
          "550",
          "575M",
          "599",
          "612",
          "812 Superfast",
          "California",
          "Dino 206 GT",
          "Dino 208/308 GT4",
          "Dino 246 GT",
          "Enzo",
          "F12berlinetta",
          "F355",
          "F40",
          "F430",
          "F50",
          "F8 Tributo",
          "FF",
          "FXX K",
          "GTC4Lusso",
          "LaFerrari",
          "Mondial",
          "Portofino",
          "SF90 Stradale",
          "Testarossa"
        ]
      },
      "Fiat": {
        "models": [
          "124",
          "124 Spider",
          "124 Sport Spider",
          "125",
          "126",
          "127",
          "128",
          "130",
          "131",
          "132",
          "238",
          "500",
          "500L",
          "500X",
          "508",
          "600",
          "900T",
          "Albea",
          "Argenta",
          "Barchetta",
          "Brava",
          "Bravo",
          "Cinquecento",
          "Coupe",
          "Croma",
          "Doblo",
          "Duna",
          "Fiorino",
          "Freemont",
          "Fullback",
          "Idea",
          "Linea",
          "Marea",
          "Multipla",
          "Palio",
          "Panda",
          "Punto",
          "Qubo",
          "Regata",
          "Ritmo",
          "Scudo",
          "Sedici",
          "Seicento",
          "Siena",
          "Stilo",
          "Strada",
          "Tempra",
          "Tipo",
          "Ulysse",
          "Uno",
          "X 1/9"
        ]
      },
      "Ford": {
        "models": [
          "Aerostar",
          "Aspire",
          "B-MAX",
          "Bronco",
          "Bronco-II",
          "C-MAX",
          "Capri",
          "Consul",
          "Contour",
          "Cortina",
          "Cougar",
          "Crown Victoria",
          "Custom",
          "Econoline",
          "EcoSport",
          "Edge",
          "Escape",
          "Escort",
          "Escort (North America)",
          "Everest",
          "Excursion",
          "Expedition",
          "Explorer",
          "Explorer Sport Trac",
          "F-150",
          "Fairlane",
          "Fairmont",
          "Falcon",
          "Festiva",
          "Fiesta",
          "Fiesta ST",
          "Five Hundred",
          "Flex",
          "Focus",
          "Focus (North America)",
          "Focus RS",
          "Focus ST",
          "Freda",
          "Freestar",
          "Freestyle",
          "Fusion",
          "Fusion (North America)",
          "Galaxie",
          "Galaxy",
          "GPA",
          "Granada",
          "Granada (North America)",
          "GT",
          "GT40",
          "Ikon",
          "Ixion",
          "KA",
          "Kuga",
          "Laser",
          "LTD Crown Victoria",
          "M151",
          "Mainline",
          "Maverick",
          "Model A",
          "Model T",
          "Mondeo",
          "Mondeo ST",
          "Mustang",
          "Orion",
          "Probe",
          "Puma",
          "Ranchero",
          "Ranger",
          "Ranger (North America)",
          "S-MAX",
          "Scorpio",
          "Sierra",
          "Spectron",
          "Taunus",
          "Taurus",
          "Taurus X",
          "Telstar",
          "Tempo",
          "Territory",
          "Thunderbird",
          "Torino",
          "Tourneo Connect",
          "Tourneo Courier",
          "Tourneo Custom",
          "Transit",
          "V8",
          "Windstar",
          "Zephyr"
        ]
      },
      "Foton": {
        "models": ["Midi", "Sauvana", "Tunland"]
      },
      "GMC": {
        "models": [
          "Acadia",
          "Canyon",
          "Envoy",
          "Jimmy",
          "Safari",
          "Savana",
          "Sierra",
          "Sonoma",
          "Suburban",
          "Syclone",
          "Terrain",
          "Typhoon",
          "Vandura",
          "Yukon"
        ]
      },
      "Geely": {
        "models": [
          "Atlas",
          "Beauty Leopard",
          "Coolray",
          "CK (Otaka)",
          "Emgrand 7",
          "Emgrand EC7",
          "Emgrand EC8",
          "Emgrand GT",
          "Emgrand X7",
          "FC (Vision)",
          "GC6",
          "GC9",
          "Haoqing",
          "LC (Panda)",
          "LC (Panda) Cross",
          "MK",
          "MK Cross",
          "MR",
          "SC7",
          "TX4"
        ]
      },
      "Genesis": {
        "models": ["G70", "G80", "GV80", "G90"]
      },
      "Geo": {
        "models": ["Metro", "Prizm", "Spectrum", "Storm", "Tracker"]
      },
      "Great Wall": {
        "models": [
          "Coolbear",
          "Cowry (V80)",
          "Deer",
          "Florid",
          "Hover",
          "Hover H3",
          "Hover H5",
          "Hover H6",
          "Hover M1 (Peri 4x4)",
          "Hover M2",
          "Hover M4",
          "Pegasus",
          "Peri",
          "Safe",
          "Sailor",
          "Sing RUV",
          "Socool",
          "Voleex C10 (Phenom)",
          "Voleex C30",
          "Wingle"
        ]
      },
      "Hafei": {
        "models": ["Brio", "Princip", "Saibao", "Sigma", "Simbo"]
      },
      "Haima": {
        "models": ["2", "3", "7", "Family", "Family F7", "Freema", "M3", "S5"]
      },
      "Hanomag": {
        "models": ["Rekord", "Typ 13"]
      },
      "Haval": {
        "models": ["F7", "H2", "H6", "H6 Coupe", "H8", "H9"]
      },
      "Hawtai": {
        "models": ["B21", "Boliger", "Laville"]
      },
      "Honda": {
        "models": [
          "145",
          "Accord",
          "Acty",
          "Airwave",
          "Ascot",
          "Ascot Innova",
          "Avancier",
          "Ballade",
          "Beat",
          "Brio",
          "Capa",
          "City",
          "Civic",
          "Civic Ferio",
          "Civic Type R",
          "Concerto",
          "CR-V",
          "CR-X",
          "CR-Z",
          "Crossroad",
          "Crosstour",
          "Domani",
          "Edix",
          "Element",
          "Elysion",
          "FCX Clarity",
          "Fit",
          "Fit Aria",
          "Fit Shuttle",
          "FR-V",
          "Freed",
          "Grace",
          "Horizon",
          "HR-V",
          "Insight",
          "Inspire",
          "Integra",
          "Integra SJ",
          "Jade",
          "Jazz",
          "Lagreat",
          "Legend",
          "Life",
          "Logo",
          "MDX",
          "Mobilio",
          "Mobilio Spike",
          "N-BOX",
          "N-One",
          "N-WGN",
          "N360",
          "NSX",
          "Odyssey",
          "Odyssey (North America)",
          "Orthia",
          "Partner",
          "Passport",
          "Pilot",
          "Prelude",
          "Quint",
          "Rafaga",
          "Ridgeline",
          "S-MX",
          "S2000",
          "S500",
          "S600",
          "S660",
          "Saber",
          "Shuttle",
          "Stepwgn",
          "Stream",
          "Street",
          "That'S",
          "Today",
          "Torneo",
          "Vamos",
          "Vezel",
          "Vigor",
          "Z",
          "Zest"
        ]
      },
      "HuangHai": {
        "models": ["Antelope", "Landscape", "Plutus"]
      },
      "Hudson": {
        "models": ["Deluxe Eight", "Super Six"]
      },
      "Hummer": {
        "models": ["H1", "H2", "H3"]
      },
      "Hyundai": {
        "models": [
          "Accent",
          "Aslan",
          "Atos",
          "Avante",
          "Azera",
          "Centennial",
          "Click",
          "Coupe",
          "Creta",
          "Dynasty",
          "Elantra",
          "Entourage",
          "EON",
          "Equus",
          "Excel",
          "Galloper",
          "Genesis",
          "Genesis Coupe",
          "Getz",
          "Grace",
          "Grand Starex",
          "Grandeur",
          "H-1",
          "H200",
          "i10",
          "i20",
          "i30",
          "i30 N",
          "i40",
          "IONIQ",
          "ix20",
          "ix35",
          "ix55",
          "Kona",
          "Lantra",
          "Lavita",
          "Marcia",
          "Matrix",
          "Maxcruz",
          "Palisade",
          "Pony",
          "Santa Fe",
          "Santamo",
          "Scoupe",
          "Solaris",
          "Sonata",
          "Starex",
          "Stellar",
          "Terracan",
          "Tiburon",
          "Trajet",
          "Tucson",
          "Tuscani",
          "Veloster",
          "Veracruz",
          "Verna",
          "XG"
        ]
      },
      "Infiniti": {
        "models": [
          "EX",
          "FX",
          "G",
          "I",
          "J",
          "JX",
          "M",
          "Q",
          "Q30",
          "Q40",
          "Q50",
          "Q60",
          "Q70",
          "QX30",
          "QX4",
          "QX50",
          "QX56",
          "QX60",
          "QX70",
          "QX80"
        ]
      },
      "International": {
        "models": ["Travelall"]
      },
      "Iran Khodro": {
        "models": ["Dena", "Paykan", "Runna", "Sahra", "Samand", "Sarir", "Soren"]
      },
      "Isuzu": {
        "models": [
          "117",
          "Amigo",
          "Ascender",
          "Aska",
          "Axiom",
          "Bellett",
          "Bighorn",
          "D-Max",
          "Fargo",
          "Fargo Filly",
          "Florian",
          "Gemini",
          "Hombre",
          "Impulse",
          "KB",
          "MU",
          "MU-7",
          "MU-X",
          "Piazza",
          "Rodeo",
          "Stylus",
          "TF (Pickup)",
          "Trooper",
          "VehiCross",
          "Wizard"
        ]
      },
      "JAC": {
        "models": [
          "iEV7S",
          "J2 (Yueyue)",
          "J3 (Tongyue,Tojoy)",
          "J4 (Heyue A30)",
          "J5 (Heyue)",
          "J6 (Heyue RS)",
          "J7 (Binyue)",
          "M1 (Refine)",
          "M5",
          "S1 (Rein)",
          "S3",
          "S5 (Eagle)",
          "T6"
        ]
      },
      "JMC": {
        "models": ["Baodian"]
      },
      "Jaguar": {
        "models": [
          "E-Pace",
          "E-type",
          "F-Pace",
          "F-Type",
          "I-Pace",
          "Mark 2",
          "S-Type",
          "X-Type",
          "XE",
          "XF",
          "XFR",
          "XJ",
          "XJ220",
          "XJR",
          "XJS",
          "XK",
          "XKR"
        ]
      },
      "Jeep": {
        "models": [
          "Cherokee",
          "CJ",
          "Commander",
          "Compass",
          "Grand Cherokee",
          "Grand Wagoneer",
          "Liberty (North America)",
          "Liberty (Patriot)",
          "Renegade",
          "Wrangler"
        ]
      },
      "Jinbei": {
        "models": ["Haise"]
      },
      "Kia": {
        "models": [
          "Avella",
          "Cadenza",
          "Capital",
          "Carens",
          "Carnival",
          "Carstar",
          "Ceed",
          "Ceed GT",
          "Cerato",
          "Clarus",
          "Concord",
          "Elan",
          "Enterprise",
          "Forte",
          "Joice",
          "K3",
          "K5",
          "K7",
          "K9",
          "K900",
          "Lotze",
          "Magentis",
          "Mentor",
          "Mohave (Borrego)",
          "Morning",
          "Niro",
          "Opirus",
          "Optima",
          "Picanto",
          "Potentia",
          "Pregio",
          "Pride",
          "Quanlima",
          "Quoris",
          "Ray",
          "Retona",
          "Rio",
          "Rio X-Line",
          "Sedona",
          "Seltos",
          "Sephia",
          "Shuma",
          "Sorento",
          "Soul",
          "Soul EV",
          "Spectra",
          "Sportage",
          "Stinger",
          "Stonic",
          "Telluride",
          "Towner",
          "Venga",
          "Visto",
          "X-Trek",
          "XCeed"
        ]
      },
      "LADA (\u0412\u0410\u0417)": {
        "models": [
          "1111 \u041e\u043a\u0430",
          "2101",
          "2102",
          "2103",
          "2104",
          "2105",
          "2106",
          "2107",
          "2108",
          "2109",
          "21099",
          "2110",
          "2111",
          "2112",
          "2113",
          "2114",
          "2115",
          "2120 \u041d\u0430\u0434\u0435\u0436\u0434\u0430",
          "2121 (4x4)",
          "2123",
          "2129",
          "2131 (4x4)",
          "2328",
          "2329",
          "EL Lada",
          "Granta",
          "Kalina",
          "Largus",
          "Priora",
          "Revolution",
          "Vesta",
          "XRAY"
        ]
      },
      "Lamborghini": {
        "models": [
          "350/400 GT",
          "Aventador",
          "Centenario",
          "Countach",
          "Diablo",
          "Egoista",
          "Espada",
          "Gallardo",
          "Hurac\u00e1n",
          "Islero",
          "Jalpa",
          "Jarama",
          "LM001",
          "LM002",
          "Miura",
          "Murcielago",
          "Reventon",
          "Sesto Elemento",
          "Silhouette",
          "Urraco",
          "Urus",
          "Veneno"
        ]
      },
      "Lancia": {
        "models": [
          "A 112",
          "Appia",
          "Aurelia",
          "Beta",
          "Dedra",
          "Delta",
          "Flaminia",
          "Flavia",
          "Fulvia",
          "Gamma",
          "Hyena",
          "Kappa",
          "Lambda",
          "Lybra",
          "Monte Carlo",
          "Musa",
          "Phedra",
          "Prisma",
          "Rally 037",
          "Stratos",
          "Thema",
          "Thesis",
          "Trevi",
          "Voyager",
          "Y10",
          "Ypsilon",
          "Zeta"
        ]
      },
      "Land Rover": {
        "models": [
          "Defender",
          "Discovery",
          "Discovery Sport",
          "Freelander",
          "Range Rover",
          "Range Rover Evoque",
          "Range Rover Sport",
          "Range Rover Velar",
          "Series I",
          "Series II",
          "Series III"
        ]
      },
      "Landwind": {
        "models": ["Fashion (CV9)", "Forward", "X5", "X6", "X7", "\u04259"]
      },
      "Lexus": {
        "models": [
          "CT",
          "ES",
          "GS",
          "GS F",
          "GX",
          "HS",
          "IS",
          "IS F",
          "LC",
          "LFA",
          "LS",
          "LX",
          "NX",
          "RC",
          "RC F",
          "RX",
          "SC",
          "UX"
        ]
      },
      "Lifan": {
        "models": [
          "Breez (520)",
          "Cebrium (720)",
          "Celliya (530)",
          "Murman (820)",
          "Myway",
          "Smily",
          "Solano",
          "X50",
          "X60",
          "X70"
        ]
      },
      "Lincoln": {
        "models": [
          "Aviator",
          "Blackwood",
          "Capri",
          "Continental",
          "Corsair",
          "LS",
          "Mark III",
          "Mark IV",
          "Mark LT",
          "Mark VII",
          "Mark VIII",
          "MKC",
          "MKS",
          "MKT",
          "MKX",
          "MKZ",
          "Nautilus",
          "Navigator",
          "Premiere",
          "Town Car"
        ]
      },
      "Lotus": {
        "models": [
          "340R",
          "Eclat",
          "Elan",
          "Elise",
          "Elite",
          "Esprit",
          "Europa",
          "Europa S",
          "Evora",
          "Excel",
          "Exige"
        ]
      },
      "Luxgen": {
        "models": ["Luxgen5", "Luxgen7 MPV", "Luxgen7 SUV", "U6 Turbo", "U7 Turbo"]
      },
      "MG": {
        "models": [
          "3",
          "350",
          "5",
          "550",
          "6",
          "750",
          "F",
          "GS",
          "Maestro",
          "Metro",
          "MGA",
          "MGB",
          "Midget",
          "Montego",
          "RV8",
          "TD Midget",
          "TF",
          "Xpower SV",
          "ZR",
          "ZS",
          "ZT"
        ]
      },
      "MINI": {
        "models": ["Cabrio", "Clubman", "Countryman", "Coupe", "Hatch", "Paceman", "Roadster"]
      },
      "Mahindra": {
        "models": [
          "Armada",
          "Bolero",
          "CJ-3",
          "CL",
          "Commander",
          "Marshal",
          "MM",
          "NC 640 DP",
          "Scorpio",
          "Verito",
          "Voyager",
          "Xylo"
        ]
      },
      "Maruti": {
        "models": [
          "1000",
          "800",
          "Alto",
          "Baleno",
          "Esteem",
          "Gypsy",
          "Omni",
          "Versa",
          "Wagon R",
          "Zen"
        ]
      },
      "Maserati": {
        "models": [
          "228",
          "3200 GT",
          "420",
          "4200 GT",
          "Barchetta Stradale",
          "Biturbo",
          "Bora",
          "Chubasco",
          "Ghibli",
          "GranTurismo",
          "Indy",
          "Karif",
          "Khamsin",
          "Kyalami",
          "Levante",
          "MC12",
          "Merak",
          "Mexico",
          "Quattroporte",
          "Royale",
          "Shamal"
        ]
      },
      "Maybach": {
        "models": ["57", "62", "Exelero"]
      },
      "Mazda": {
        "models": [
          "1000",
          "121",
          "1300",
          "2",
          "3",
          "3 MPS",
          "323",
          "5",
          "6",
          "6 MPS",
          "616",
          "626",
          "818",
          "929",
          "Atenza",
          "Autozam AZ-3",
          "Axela",
          "AZ-1",
          "AZ-Offroad",
          "AZ-Wagon",
          "B-series",
          "Biante",
          "Bongo",
          "Bongo Friendee",
          "BT-50",
          "Capella",
          "Carol",
          "Chantez",
          "Cosmo",
          "Cronos",
          "CX-3",
          "CX-30",
          "CX-5",
          "CX-7",
          "CX-8",
          "CX-9",
          "Demio",
          "Efini MS-6",
          "Efini MS-8",
          "Efini MS-9",
          "Etude",
          "Eunos 100",
          "Eunos 300",
          "Eunos 500",
          "Eunos 800",
          "Eunos Cosmo",
          "Familia",
          "Flair",
          "Flair Crossover",
          "Lantis",
          "Laputa",
          "Luce",
          "Millenia",
          "MPV",
          "MX-3",
          "MX-5",
          "MX-6",
          "Navajo",
          "Persona",
          "Premacy",
          "Proceed",
          "Proceed Levante",
          "Proceed Marvie",
          "Protege",
          "R360",
          "Revue",
          "Roadster",
          "RX-7",
          "RX-8",
          "Scrum",
          "Sentia",
          "Spiano",
          "Tribute",
          "Verisa",
          "Xedos 6",
          "Xedos 9"
        ]
      },
      "McLaren": {
        "models": ["540C", "570GT", "570S", "600LT", "650S", "675LT", "720S", "F1", "MP4-12C", "P1"]
      },
      "Mercedes-Benz": {
        "models": [
          "190 (W201)",
          "190 SL",
          "A-klasse",
          "A-klasse AMG",
          "AMG GT",
          "B-klasse",
          "C-klasse",
          "C-klasse AMG",
          "Citan",
          "CL-klasse",
          "CL-klasse AMG",
          "CLA-klasse",
          "CLA-klasse AMG",
          "CLC-klasse",
          "CLK-klasse",
          "CLK-klasse AMG",
          "CLS-klasse",
          "CLS-klasse AMG",
          "E-klasse",
          "E-klasse AMG",
          "EQC",
          "G-klasse",
          "G-klasse AMG",
          "G-klasse AMG 6x6",
          "GL-klasse",
          "GL-klasse AMG",
          "GLA-klasse",
          "GLA-klasse AMG",
          "GLB",
          "GLC",
          "GLC AMG",
          "GLC Coupe",
          "GLC Coupe AMG",
          "GLE",
          "GLE AMG",
          "GLE Coupe",
          "GLE Coupe AMG",
          "GLK-klasse",
          "GLS-klasse",
          "GLS-klasse AMG",
          "M-klasse",
          "M-klasse AMG",
          "Maybach G 650 Landaulet",
          "Maybach S-klasse",
          "R-klasse",
          "R-klasse AMG",
          "S-klasse",
          "S-klasse AMG",
          "SL-klasse",
          "SL-klasse AMG",
          "SLC-klasse",
          "SLC-klasse AMG",
          "SLK-klasse",
          "SLK-klasse AMG",
          "SLR McLaren",
          "SLS AMG",
          "V-klasse",
          "Vaneo",
          "Viano",
          "Vito",
          "W100",
          "W105",
          "W108",
          "W110",
          "W111",
          "W114",
          "W115",
          "W120",
          "W121",
          "W123",
          "W124",
          "W128",
          "W136",
          "W142",
          "W186",
          "W188",
          "W189",
          "W191",
          "W29",
          "X-klasse"
        ]
      },
      "Mercury": {
        "models": [
          "Capri",
          "Cougar",
          "Eight",
          "Grand Marquis",
          "Marauder",
          "Mariner",
          "Marquis",
          "Milan",
          "Montego",
          "Monterey",
          "Mountaineer",
          "Mystique",
          "Sable",
          "Topaz",
          "Tracer",
          "Villager"
        ]
      },
      "Metrocab": {
        "models": ["Metrocab I", "Metrocab II (TTT)"]
      },
      "Mitsubishi": {
        "models": [
          "3000 GT",
          "500",
          "Airtrek",
          "Aspire",
          "ASX",
          "Attrage",
          "Carisma",
          "Celeste",
          "Challenger",
          "Chariot",
          "Colt",
          "Cordia",
          "Debonair",
          "Delica",
          "Delica D:2",
          "Delica D:3",
          "Delica D:5",
          "Diamante",
          "Dignity",
          "Dingo",
          "Dion",
          "Eclipse",
          "Eclipse Cross",
          "eK Active",
          "eK Classic",
          "eK Custom",
          "eK Space",
          "eK Sport",
          "eK Wagon",
          "Emeraude",
          "Endeavor",
          "Eterna",
          "Freeca",
          "FTO",
          "Galant",
          "Galant Fortis",
          "Grandis",
          "GTO",
          "i",
          "i-MiEV",
          "Jeep J",
          "L200",
          "L300",
          "L400",
          "Lancer",
          "Lancer Cargo",
          "Lancer Evolution",
          "Lancer Ralliart",
          "Legnum",
          "Libero",
          "Minica",
          "Minicab",
          "Mirage",
          "Montero",
          "Montero Sport",
          "Outlander",
          "Pajero",
          "Pajero iO",
          "Pajero Junior",
          "Pajero Mini",
          "Pajero Pinin",
          "Pajero Sport",
          "Pistachio",
          "Proudia",
          "Raider",
          "RVR",
          "Sapporo",
          "Savrin",
          "Sigma",
          "Space Gear",
          "Space Runner",
          "Space Star",
          "Space Wagon",
          "Starion",
          "Strada",
          "Toppo",
          "Town Box",
          "Tredia",
          "Triton",
          "Xpander"
        ]
      },
      "Mitsuoka": {
        "models": [
          "Galue",
          "Galue 204",
          "Himiko",
          "Le-Seyde",
          "Like",
          "MC-1",
          "Nouera",
          "Orochi",
          "Ray",
          "Rock Star",
          "Ryoga",
          "Ryugi",
          "Viewt",
          "Yuga",
          "Zero 1"
        ]
      },
      "Morgan": {
        "models": [
          "3 Wheeler",
          "4 Seater",
          "4/4",
          "Aero 8",
          "Aero Coupe",
          "Aero SuperSports",
          "AeroMax",
          "Plus 4",
          "Plus 8",
          "Roadster"
        ]
      },
      "Morris": {
        "models": ["Eight", "Marina"]
      },
      "Nissan": {
        "models": [
          "100NX",
          "180SX",
          "200SX",
          "240SX",
          "280ZX",
          "300ZX",
          "350Z",
          "370Z",
          "AD",
          "Almera",
          "Almera Classic",
          "Almera Tino",
          "Altima",
          "Armada",
          "Auster",
          "Avenir",
          "Bassara",
          "BE-1",
          "Bluebird",
          "Bluebird Maxima",
          "Bluebird Sylphy",
          "Caravan",
          "Cedric",
          "Cefiro",
          "Cherry",
          "Cima",
          "Clipper Rio",
          "Crew",
          "Cube",
          "Datsun",
          "Dayz",
          "Dayz Roox",
          "Dualis",
          "Elgrand",
          "Exa",
          "Expert",
          "Fairlady Z",
          "Figaro",
          "Fuga",
          "Gloria",
          "GT-R",
          "Homy",
          "Hypermini",
          "Juke",
          "Juke Nismo",
          "Kicks",
          "Kix",
          "Lafesta",
          "Langley",
          "Largo",
          "Latio",
          "Laurel",
          "Leaf",
          "Leopard",
          "Liberta Villa",
          "Liberty",
          "Livina",
          "Lucino",
          "March",
          "Maxima",
          "Micra",
          "Mistral",
          "Moco",
          "Murano",
          "Navara (Frontier)",
          "Note",
          "NP300",
          "NV100 Clipper",
          "NV200",
          "NV350 Caravan",
          "NX Coupe",
          "Otti",
          "Pao",
          "Pathfinder",
          "Patrol",
          "Pino",
          "Pixo",
          "Prairie",
          "Presage",
          "Presea",
          "President",
          "Primastar",
          "Primera",
          "Pulsar",
          "Qashqai",
          "Qashqai+2",
          "Quest",
          "R'nessa",
          "Rasheen",
          "Rogue",
          "Roox",
          "Safari",
          "Sentra",
          "Serena",
          "Silvia",
          "Skyline",
          "Skyline Crossover",
          "Stagea",
          "Stanza",
          "Sunny",
          "Teana",
          "Terra",
          "Terrano",
          "Terrano Regulus",
          "Tiida",
          "Tino",
          "Titan",
          "Urvan",
          "Vanette",
          "Versa",
          "Wingroad",
          "X-Trail",
          "Xterra"
        ]
      },
      "Oldsmobile": {
        "models": [
          "Achieva",
          "Alero",
          "Aurora",
          "Bravada",
          "Cutlass",
          "Cutlass Calais",
          "Cutlass Ciera",
          "Cutlass Supreme",
          "Eighty-Eight",
          "Firenza",
          "Intrigue",
          "Ninety-Eight",
          "Omega",
          "Series 60",
          "Series 70",
          "Silhouette",
          "Starfire",
          "Toronado",
          "Vista Cruiser"
        ]
      },
      "Opel": {
        "models": [
          "Adam",
          "Admiral",
          "Agila",
          "Ampera",
          "Antara",
          "Ascona",
          "Astra",
          "Astra OPC",
          "Calibra",
          "Campo",
          "Cascada",
          "Combo",
          "Commodore",
          "Corsa",
          "Corsa OPC",
          "Crossland X",
          "Diplomat",
          "Frontera",
          "Grandland X",
          "GT",
          "Insignia",
          "Insignia OPC",
          "Kadett",
          "Kapitan",
          "Karl",
          "Manta",
          "Meriva",
          "Meriva OPC",
          "Mokka",
          "Monterey",
          "Monza",
          "Olympia",
          "Omega",
          "P4",
          "Rekord",
          "Senator",
          "Signum",
          "Sintra",
          "Speedster",
          "Super Six",
          "Tigra",
          "Vectra",
          "Vectra OPC",
          "Vita",
          "Vivaro",
          "Zafira",
          "Zafira OPC"
        ]
      },
      "PUCH": {
        "models": ["G-modell", "Pinzgauer"]
      },
      "Packard": {
        "models": ["200/250", "Clipper", "Custom Eight", "One-Twenty", "Twelve"]
      },
      "Peugeot": {
        "models": [
          "1007",
          "104",
          "106",
          "107",
          "108",
          "2008",
          "201",
          "202",
          "203",
          "204",
          "205",
          "205 GTi",
          "206",
          "207",
          "208",
          "208 GTi",
          "3008",
          "301",
          "304",
          "305",
          "306",
          "307",
          "308",
          "308 GTi",
          "309",
          "4007",
          "4008",
          "402",
          "403",
          "404",
          "405",
          "406",
          "407",
          "408",
          "5008",
          "504",
          "505",
          "508",
          "604",
          "605",
          "607",
          "806",
          "807",
          "Bipper",
          "Boxer",
          "Expert",
          "iOn",
          "Partner",
          "RCZ",
          "Rifter",
          "Traveller"
        ]
      },
      "Plymouth": {
        "models": [
          "Acclaim",
          "Barracuda",
          "Breeze",
          "Caravelle",
          "Fury",
          "Horizon",
          "Laser",
          "Neon",
          "Prowler",
          "Reliant",
          "Road Runner",
          "Satellite",
          "Sundance",
          "Turismo",
          "Valiant",
          "Volare",
          "Voyager"
        ]
      },
      "Pontiac": {
        "models": [
          "6000",
          "Aztek",
          "Bonneville",
          "Catalina",
          "Fiero",
          "Firebird",
          "G4",
          "G5",
          "G6",
          "G8",
          "Grand AM",
          "Grand Prix",
          "GTO",
          "Laurentian",
          "LeMans",
          "Montana",
          "Parisienne",
          "Phoenix",
          "Solstice",
          "Sunbird",
          "Sunfire",
          "Tempest",
          "Torpedo",
          "Torrent",
          "Trans Sport",
          "Vibe"
        ]
      },
      "Porsche": {
        "models": [
          "356",
          "718 Spyder",
          "911",
          "911 GT2",
          "911 GT3",
          "911 R",
          "912",
          "914",
          "918 Spyder",
          "924",
          "928",
          "944",
          "959",
          "968",
          "Boxster",
          "Carrera GT",
          "Cayenne",
          "Cayman",
          "Cayman GT4",
          "Macan",
          "Panamera",
          "Taycan"
        ]
      },
      "Proton": {
        "models": [
          "Arena",
          "Exora",
          "Gen-2",
          "Inspira",
          "Juara",
          "Perdana",
          "Persona",
          "Preve",
          "Putra",
          "Saga",
          "Satria",
          "Savvy",
          "Tiara",
          "Waja",
          "Wira (400 Series)"
        ]
      },
      "Rambler": {
        "models": ["Ambassador"]
      },
      "Ravon": {
        "models": ["Gentra", "Matiz", "Nexia R3", "R2", "R4"]
      },
      "Renault": {
        "models": [
          "10",
          "11",
          "12",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "25",
          "30",
          "4",
          "4CV",
          "5",
          "6",
          "8",
          "9",
          "Alaskan",
          "Arkana",
          "Avantime",
          "Captur",
          "Caravelle",
          "Clio",
          "Clio RS",
          "Clio V6",
          "Dauphine",
          "Dokker",
          "Duster",
          "Espace",
          "Floride",
          "Fluence",
          "Fregate",
          "Fuego",
          "Kadjar",
          "Kangoo",
          "Kaptur",
          "Koleos",
          "KWID",
          "Laguna",
          "Latitude",
          "Lodgy",
          "Logan",
          "Master",
          "Megane",
          "Megane RS",
          "Modus",
          "Rodeo",
          "Safrane",
          "Sandero",
          "Sandero RS",
          "Scenic",
          "Sport Spider",
          "Symbol",
          "Talisman",
          "Trafic",
          "Twingo",
          "Twizy",
          "Vel Satis",
          "Vivastella",
          "Wind",
          "ZOE"
        ]
      },
      "Renault Samsung": {
        "models": ["QM5", "QM6", "SM3", "SM5", "SM7"]
      },
      "Rimac": {
        "models": ["C Two", "Concept_One"]
      },
      "Rolls-Royce": {
        "models": [
          "20/25",
          "Camargue",
          "Corniche",
          "Cullinan",
          "Dawn",
          "Ghost",
          "Park Ward",
          "Phantom",
          "Silver Cloud",
          "Silver Ghost",
          "Silver Seraph",
          "Silver Shadow",
          "Silver Spirit",
          "Silver Spur",
          "Silver Wraith",
          "Wraith"
        ]
      },
      "Rover": {
        "models": [
          "100",
          "14",
          "200",
          "25",
          "400",
          "45",
          "600",
          "75",
          "800",
          "Maestro",
          "Metro",
          "Mini",
          "P3",
          "P4",
          "P6",
          "SD1",
          "Streetwise"
        ]
      },
      "SEAT": {
        "models": [
          "133",
          "Alhambra",
          "Altea",
          "Arona",
          "Arosa",
          "Ateca",
          "Cordoba",
          "Exeo",
          "Fura",
          "Ibiza",
          "Ibiza Cupra",
          "Inca",
          "Leon",
          "Leon Cupra",
          "Malaga",
          "Marbella",
          "Mii",
          "Ronda",
          "Tarraco",
          "Toledo"
        ]
      },
      "Saab": {
        "models": [
          "600",
          "9-2X",
          "9-3",
          "9-4X",
          "9-5",
          "9-7X",
          "90",
          "900",
          "9000",
          "93",
          "95",
          "96",
          "99",
          "Sonett"
        ]
      },
      "Saturn": {
        "models": [
          "Astra",
          "Aura",
          "ION",
          "LS",
          "LW",
          "Outlook",
          "Relay",
          "SC",
          "Sky",
          "SL",
          "SW",
          "VUE"
        ]
      },
      "Scion": {
        "models": ["FR-S", "iA", "iM", "iQ", "tC", "xA", "xB", "xD"]
      },
      "Shanghai Maple": {
        "models": ["C31", "C32", "C51", "C52", "C61", "C81"]
      },
      "ShuangHuan": {
        "models": ["Noble", "Sceo"]
      },
      "Skoda": {
        "models": [
          "100 Series",
          "105, 120",
          "1200",
          "Citigo",
          "Fabia",
          "Fabia RS",
          "Favorit",
          "Felicia",
          "Forman",
          "Kamiq",
          "Karoq",
          "Kodiaq",
          "Kodiaq RS",
          "Octavia",
          "Octavia RS",
          "Popular",
          "Rapid",
          "Roomster",
          "Scala",
          "Superb",
          "Yeti"
        ]
      },
      "Smart": {
        "models": ["Forfour", "Fortwo", "Roadster"]
      },
      "SsangYong": {
        "models": [
          "Actyon",
          "Actyon Sports",
          "Chairman",
          "Istana",
          "Kallista",
          "Korando",
          "Korando Family",
          "Korando Sports",
          "Korando Turismo",
          "Kyron",
          "Musso",
          "Nomad",
          "Rexton",
          "Rodius",
          "Stavic",
          "Tivoli",
          "XLV"
        ]
      },
      "Steyr": {
        "models": ["1500"]
      },
      "Subaru": {
        "models": [
          "1000",
          "360",
          "Alcyone",
          "Ascent",
          "Baja",
          "Bighorn",
          "Bistro",
          "Brat",
          "BRZ",
          "Dex",
          "Dias Wagon",
          "Domingo",
          "Exiga",
          "Forester",
          "Impreza",
          "Impreza WRX",
          "Impreza WRX STi",
          "Justy",
          "Legacy",
          "Legacy Lancaster",
          "Leone",
          "Levorg",
          "Libero",
          "Lucra",
          "Outback",
          "Pleo",
          "R1",
          "R2",
          "Rex",
          "Sambar",
          "Stella",
          "SVX",
          "Traviq",
          "Trezia",
          "Tribeca",
          "Vivio",
          "WRX",
          "WRX STi",
          "XT",
          "XV"
        ]
      },
      "Suzuki": {
        "models": [
          "Aerio",
          "Alto",
          "Alto Lapin",
          "APV",
          "Baleno",
          "Cappuccino",
          "Cara",
          "Carry",
          "Celerio",
          "Cervo",
          "Cultus",
          "Equator",
          "Ertiga",
          "Escudo",
          "Esteem",
          "Every",
          "Forenza",
          "Grand Vitara",
          "Hustler",
          "Ignis",
          "Jimny",
          "Kei",
          "Kizashi",
          "Landy",
          "Liana",
          "MR Wagon",
          "Palette",
          "Reno",
          "Samurai",
          "Sidekick",
          "Solio",
          "Spacia",
          "Splash",
          "Swift",
          "SX4",
          "Twin",
          "Verona",
          "Vitara",
          "Wagon R",
          "Wagon R+",
          "X-90",
          "XL7"
        ]
      },
      "TATA": {
        "models": [
          "Aria",
          "Estate",
          "Indica",
          "Indigo",
          "Nano",
          "Safari",
          "Sierra",
          "Sumo",
          "Sumo Grande",
          "Telcoline",
          "Xenon"
        ]
      },
      "Talbot": {
        "models": ["1510", "Avenger", "Horizon", "Rancho", "Samba", "Solara", "Tagora"]
      },
      "Tatra": {
        "models": ["57", "77", "80", "87", "T603", "T613", "T700"]
      },
      "Tesla": {
        "models": ["Model 3", "Model S", "Model X", "Roadster"]
      },
      "Tianma": {
        "models": ["Century"]
      },
      "Tianye": {
        "models": ["Admiral"]
      },
      "Toyota": {
        "models": [
          "2000GT",
          "4Runner",
          "Allex",
          "Allion",
          "Alphard",
          "Altezza",
          "Aqua",
          "Aristo",
          "Aurion",
          "Auris",
          "Avalon",
          "Avanza",
          "Avensis",
          "Avensis Verso",
          "Aygo",
          "bB",
          "Belta",
          "Blade",
          "Blizzard",
          "Brevis",
          "C-HR",
          "Caldina",
          "Cami",
          "Camry",
          "Camry Solara",
          "Carina",
          "Carina E",
          "Carina ED",
          "Cavalier",
          "Celica",
          "Celsior",
          "Century",
          "Chaser",
          "Classic",
          "Comfort",
          "COMS",
          "Corolla",
          "Corolla II",
          "Corolla Rumion",
          "Corolla Spacio",
          "Corolla Verso",
          "Corona",
          "Corona EXiV",
          "Corsa",
          "Cressida",
          "Cresta",
          "Crown",
          "Crown Majesta",
          "Curren",
          "Cynos",
          "Duet",
          "Echo",
          "Esquire",
          "Estima",
          "Etios",
          "FJ Cruiser",
          "Fortuner",
          "FunCargo",
          "Gaia",
          "Grand HiAce",
          "Granvia",
          "GT86",
          "Harrier",
          "HiAce",
          "Highlander",
          "Hilux",
          "Hilux Surf",
          "Innova",
          "Ipsum",
          "iQ",
          "ISis",
          "Ist",
          "Kluger",
          "Land Cruiser",
          "Land Cruiser Prado",
          "Lite Ace",
          "Mark II",
          "Mark X",
          "Mark X ZiO",
          "MasterAce Surf",
          "Matrix",
          "Mega Cruiser",
          "Mirai",
          "Model F",
          "MR-S",
          "MR2",
          "Nadia",
          "Noah",
          "Opa",
          "Origin",
          "Paseo",
          "Passo",
          "Passo Sette",
          "Picnic",
          "Pixis Epoch",
          "Pixis Mega",
          "Pixis Space",
          "Platz",
          "Porte",
          "Premio",
          "Previa",
          "Prius",
          "Prius Alpha",
          "Prius c",
          "Prius v (+)",
          "ProAce",
          "Probox",
          "Progres",
          "Pronard",
          "Publica",
          "Ractis",
          "Raum",
          "RAV 4",
          "Regius",
          "RegiusAce",
          "Rush",
          "Sai",
          "Scepter",
          "Sequoia",
          "Sera",
          "Sienna",
          "Sienta",
          "Soarer",
          "Soluna",
          "Spade",
          "Sparky",
          "Sports 800",
          "Sprinter",
          "Sprinter Carib",
          "Sprinter Marino",
          "Sprinter Trueno",
          "Starlet",
          "Succeed",
          "Supra",
          "Tacoma",
          "Tercel",
          "Touring HiAce",
          "Town Ace",
          "Tundra",
          "Urban Cruiser",
          "Vanguard",
          "Vellfire",
          "Venza",
          "Verossa",
          "Verso",
          "Verso-S",
          "Vios",
          "Vista",
          "Vitz",
          "Voltz",
          "Voxy",
          "WiLL",
          "WiLL Cypha",
          "Windom",
          "Wish",
          "Yaris",
          "Yaris Verso"
        ]
      },
      "Trabant": {
        "models": ["1.1", "600", "P 601", "P50"]
      },
      "Triumph": {
        "models": ["Acclaim", "Spitfire", "Stag", "TR4", "TR6", "TR7", "TR8"]
      },
      "Vauxhall": {
        "models": [
          "Adam",
          "Astra",
          "Carlton",
          "Cavalier",
          "Chevette",
          "Firenza",
          "Omega",
          "Royale",
          "Vectra",
          "Velox",
          "Ventora",
          "Viceroy",
          "Victor",
          "Viva",
          "VXR8"
        ]
      },
      "Volkswagen": {
        "models": [
          "181",
          "Amarok",
          "Arteon",
          "Beetle",
          "Bora",
          "Caddy",
          "California",
          "Caravelle",
          "Corrado",
          "Derby",
          "Eos",
          "EuroVan",
          "Fox",
          "Gol",
          "Golf",
          "Golf Country",
          "Golf GTI",
          "Golf Plus",
          "Golf R",
          "Golf R32",
          "Golf Sportsvan",
          "ID.3",
          "Iltis",
          "Jetta",
          "K70",
          "Karmann-Ghia",
          "Lupo",
          "Lupo GTI",
          "Multivan",
          "Parati",
          "Passat",
          "Passat (North America)",
          "Passat CC",
          "Phaeton",
          "Pointer",
          "Polo",
          "Polo GTI",
          "Polo R WRC",
          "Quantum",
          "Routan",
          "Santana",
          "Scirocco",
          "Scirocco R",
          "Sharan",
          "T-Cross",
          "T-Roc",
          "Taro",
          "Teramont",
          "Tiguan",
          "Touareg",
          "Touran",
          "Transporter",
          "Type 1",
          "Type 2",
          "Type 3",
          "Type 4",
          "up!",
          "Vento",
          "XL1"
        ]
      },
      "Volvo": {
        "models": [
          "120 Series",
          "140 Series",
          "164",
          "240 Series",
          "260 Series",
          "300 Series",
          "440",
          "460",
          "480",
          "66",
          "740",
          "760",
          "780",
          "850",
          "940",
          "960",
          "C30",
          "C70",
          "Laplander",
          "P1800",
          "P1900",
          "S40",
          "S60",
          "S60 Cross Country",
          "S70",
          "S80",
          "S90",
          "V40",
          "V40 Cross Country",
          "V50",
          "V60",
          "V60 Cross Country",
          "V70",
          "V90",
          "V90 Cross Country",
          "XC40",
          "XC60",
          "XC70",
          "XC90"
        ]
      },
      "Vortex": {
        "models": ["Corda", "Estina", "Tingo"]
      },
      "Wanderer": {
        "models": ["W23", "W50"]
      },
      "Wartburg": {
        "models": ["1.3", "353"]
      },
      "Willys": {
        "models": ["Knight Model 20", "MB"]
      },
      "Xin Kai": {
        "models": ["Pickup X3", "SR-V X3", "SUV X3"]
      },
      "ZX": {
        "models": ["Admiral", "Grand Tiger", "Landmark"]
      },
      "Zenvo": {
        "models": ["ST1"]
      },
      "Zotye": {
        "models": ["Coupa", "Nomad (RX6400)", "SR9", "T600", "Z100", "Z300"]
      },
      "\u0401-\u043c\u043e\u0431\u0438\u043b\u044c": {
        "models": ["\u0401-\u041a\u0440\u043e\u0441\u0441\u043e\u0432\u0435\u0440"]
      },
      "\u0410\u0432\u0442\u043e\u043a\u0430\u043c": {
        "models": ["2160", "2163", "3101"]
      },
      "\u0413\u0410\u0417": {
        "models": [
          "12 \u0417\u0418\u041c",
          "13 \u00ab\u0427\u0430\u0439\u043a\u0430\u00bb",
          "14 \u00ab\u0427\u0430\u0439\u043a\u0430\u00bb",
          "18",
          "21 \u00ab\u0412\u043e\u043b\u0433\u0430\u00bb",
          "22 \u00ab\u0412\u043e\u043b\u0433\u0430\u00bb",
          "2308 \u00ab\u0410\u0442\u0430\u043c\u0430\u043d\u00bb",
          "2330 \u00ab\u0422\u0438\u0433\u0440\u00bb",
          "24 \u00ab\u0412\u043e\u043b\u0433\u0430\u00bb",
          "3102 \u00ab\u0412\u043e\u043b\u0433\u0430\u00bb",
          "31029 \u00ab\u0412\u043e\u043b\u0433\u0430\u00bb",
          "3103 \u00ab\u0412\u043e\u043b\u0433\u0430\u00bb",
          "3105 \u00ab\u0412\u043e\u043b\u0433\u0430\u00bb",
          "3110 \u00ab\u0412\u043e\u043b\u0433\u0430\u00bb",
          "31105 \u00ab\u0412\u043e\u043b\u0433\u0430\u00bb",
          "3111 \u00ab\u0412\u043e\u043b\u0433\u0430\u00bb",
          "46",
          "61",
          "64",
          "67",
          "69",
          "Volga Siber",
          "\u0410",
          "\u041c-20 \u00ab\u041f\u043e\u0431\u0435\u0434\u0430\u00bb",
          "\u041c-72",
          "\u041c1"
        ]
      },
      "\u0413\u043e\u043d\u043e\u0447\u043d\u044b\u0439 \u0431\u043e\u043b\u0438\u0434": {
        "models": [
          "Dallara F399/300",
          "\u0428\u043e\u0443-\u043a\u0430\u0440 \u00ab\u0424\u043e\u0440\u043c\u0443\u043b\u0430-1\u00bb"
        ]
      },
      "\u0417\u0410\u0417": {
        "models": [
          "1102 \u00ab\u0422\u0430\u0432\u0440\u0438\u044f\u00bb",
          "1103 \u00ab\u0421\u043b\u0430\u0432\u0443\u0442\u0430\u00bb",
          "1105 \u00ab\u0414\u0430\u043d\u0430\u00bb",
          "965",
          "966",
          "968",
          "Chance",
          "Forza",
          "Lanos",
          "Sens",
          "Vida"
        ]
      },
      "\u0417\u0418\u041b": {
        "models": ["111", "114", "117", "4104"]
      },
      "\u0417\u0438\u0421": {
        "models": ["101", "110"]
      },
      "\u0418\u0416": {
        "models": [
          "2125 \u00ab\u041a\u043e\u043c\u0431\u0438\u00bb",
          "2126 \u00ab\u041e\u0434\u0430\u00bb",
          "21261 \u00ab\u0424\u0430\u0431\u0443\u043b\u0430\u00bb",
          "2717",
          "\u041c\u043e\u0441\u043a\u0432\u0438\u0447-412"
        ]
      },
      "\u041b\u0443\u0410\u0417": {
        "models": ["1302 \u0412\u043e\u043b\u044b\u043d\u044c", "967", "969"]
      },
      "\u041c\u043e\u0441\u043a\u0432\u0438\u0447": {
        "models": [
          "2136",
          "2137",
          "2138",
          "2140",
          "2141",
          "2142",
          "400",
          "401",
          "402",
          "403",
          "407",
          "408",
          "410",
          "411",
          "412",
          "423",
          "424",
          "426",
          "427",
          "\u0414\u0443\u044d\u0442",
          "\u0418\u0432\u0430\u043d \u041a\u0430\u043b\u0438\u0442\u0430",
          "\u041a\u043d\u044f\u0437\u044c \u0412\u043b\u0430\u0434\u0438\u043c\u0438\u0440",
          "\u0421\u0432\u044f\u0442\u043e\u0433\u043e\u0440",
          "\u042e\u0440\u0438\u0439 \u0414\u043e\u043b\u0433\u043e\u0440\u0443\u043a\u0438\u0439"
        ]
      },
      "\u0421\u041c\u0417": {
        "models": ["\u0421-3\u0410", "\u0421-3\u0414"]
      },
      "\u0422\u0430\u0433\u0410\u0417": {
        "models": ["Aquila", "C-30", "C10", "C190", "Road Partner", "Tager", "Vega"]
      },
      "\u0423\u0410\u0417": {
        "models": [
          "3151",
          "3153",
          "3159",
          "3160",
          "3162 Simbir",
          "469",
          "Hunter",
          "Patriot",
          "Pickup"
        ]
      }
};
